### ISSUE TITLE
Admin page children )

### ISSUE THREAD

**Issue by podarok** [drupal-ukraine/advanced_forum#24]
Due to https://github.com/drupal-ukraine/advanced_forum/issues/11
We need to fix submit handler for admin page for ability to get form storing options.
Due to changes about variables->config we can start to work on migrations of changed variables for future upgrade path
- [x] Define default values for form configs #27 
- [x] Fix all @d7 todo items within a form (small issues, can be splitted) #28 
- [x] Approach submit callback #27 
- [ ] Add migration for variables->config for future D7->D8 upgrade

**Comment by podarok** [comment]
#27 needs review @Sanchiz
